dist: trusty
sudo: required
language: rust
services:
- docker
cache:
  directories:
  - "~/.npm"
notifications:
  email: false

install:
  - cargo --version
  - docker --version
  - wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-add-repository "deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-7 main"
  - sudo apt-add-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main"
  - sudo apt-get update
  - sudo apt-get install -y clang-7 --allow-unauthenticated
  - clang-7 --version
  - nvm install node
  - node --version
  - npm install

script:
  - npm run build:bpf
  - npm run test

before_deploy:
  - git add -f dist/program/tictactoe.so
  - git commit -m dist/program/tictactoe.so

deploy:
  - provider: heroku
    api_key:
      secure: HEBXce1uoy39R9vF9rQiE26rOVbfYqUHLsEG5/59LGAT28jMTiuRqHHMPDFSQytFo4qRJyorPHJrYNUdL4ur6VBGApxR/ULOVFNySGuC6+gXRT9tPbqD17596DJ98NGETBTB1mzLdoQcy6qlSLqz2rGdlfOvEsupQ65NvivxkTWtQSEWxmci5SzTjmFoUWC72ixkShXfk1me9C6QlyEyTJFMvVVbd2wxeMYQQMZoyB6ZFqBBXkMPJxNFeReG0euYX9RRXUV+YJ9FqdDqtIHYx74aTm3JihHQq2dRqVs0/lU1dGpETFqkyBG3jfYvagOSaKVtM1sjf9gp3EgOGOgyPJQZJKMTqx7FkAGB8R9BUeDu2nNRt6e20j4MDZwh0qgNlIO+jbGK+yVO3+UKPYgYTEmx3mKguwv65ihnNTwDhDBKStwXkDib42/3BLDuWNYjskshuEmgyLXCPUxn9hka5hzbx0/WBr3HrNs3K9r2pygKwPumAS1Y0BB1iscOjYQiqQjtAP5wVxfRfTcmNDuUZjyovVuV4SS+B4G9XpHpE8kh5khfnQ3SPnJPAvXuqAnbNd3mXeQJXBa3kpAHvBE9AKdsFyh7+vc+dtMdhbN+d4fIJbxQqWAI7f9FqnbcCwHd6qk2xDZILlc8B5FGRexpwVwzyz2zi7/2atFjs84kDug=
    app: solana-example-tictactoe
    strategy: git
    on:
      repo: solana-labs/example-tictactoe
      branch: master
      tags: true
  - provider: heroku
    api_key:
      secure: HEBXce1uoy39R9vF9rQiE26rOVbfYqUHLsEG5/59LGAT28jMTiuRqHHMPDFSQytFo4qRJyorPHJrYNUdL4ur6VBGApxR/ULOVFNySGuC6+gXRT9tPbqD17596DJ98NGETBTB1mzLdoQcy6qlSLqz2rGdlfOvEsupQ65NvivxkTWtQSEWxmci5SzTjmFoUWC72ixkShXfk1me9C6QlyEyTJFMvVVbd2wxeMYQQMZoyB6ZFqBBXkMPJxNFeReG0euYX9RRXUV+YJ9FqdDqtIHYx74aTm3JihHQq2dRqVs0/lU1dGpETFqkyBG3jfYvagOSaKVtM1sjf9gp3EgOGOgyPJQZJKMTqx7FkAGB8R9BUeDu2nNRt6e20j4MDZwh0qgNlIO+jbGK+yVO3+UKPYgYTEmx3mKguwv65ihnNTwDhDBKStwXkDib42/3BLDuWNYjskshuEmgyLXCPUxn9hka5hzbx0/WBr3HrNs3K9r2pygKwPumAS1Y0BB1iscOjYQiqQjtAP5wVxfRfTcmNDuUZjyovVuV4SS+B4G9XpHpE8kh5khfnQ3SPnJPAvXuqAnbNd3mXeQJXBa3kpAHvBE9AKdsFyh7+vc+dtMdhbN+d4fIJbxQqWAI7f9FqnbcCwHd6qk2xDZILlc8B5FGRexpwVwzyz2zi7/2atFjs84kDug=
    app: solana-edge-example-tictactoe
    strategy: git
    on:
      repo: solana-labs/example-tictactoe
      branch: master
  - provider: heroku
    api_key:
      secure: XaaKHG6QIDOrLG2xhuSMnZrADsEk3ts78vEUe52qbfvgeDeIEd3dwGmcuwOV14oTQSe0gX8SB4HEjIxRl5WKy1e1+njip/ocnInBUoV0Jqb0JqXZTeAwQYeicIlIo0yP1YSF/EUrb7N6SPWTkZ8njlmybt4sOiuIXbiLXX1b5EQcqfgGotH/isRh/oNRVAe/sMSf9HDlxZiGlP+N5/IC51zijeeixxwQX5rDPtFxJMxZUkNwqqqx/sej+o6MwptUWoDlwpXnxQ1C1HjafvaC9oQSm0kqJEkpBNPvGHJdi1IdFeOkRmGluRL0Wk2uwM6fYHWm98PirJ0WMWQ9RghXR4Hq8w8OYepzJdZ/p3mSFZ895bmiRui4u5N8y9Jd1gNK4zb43JC58F75ynm3RcaPLqzD597rPebYVyFu720fqCJSeZCRN+hku2j+nZIvaRx0EsZ5Fy4/jdV/a+u3+OWgx/HEfuVnWzl9V/maU3e98f7Zsu/SkA4kEKpUtsvUBFW+qHk3Pm8zwVcxQTsZyRA0EPd/QHEVrCQntYfANS4wAh3BakMf9FFVRhev8nlgEdFlSMszmk6C5w5MiB6U2Rco57fXYnOHQ6uP9MWIKDrJxaBmDuAS0jIdAGX12OJNJOOFll53QArwqB0LBLmVfr8BInFuMsZK97BthNx/ozGyFjM=
    app: solana-custom-testnet-ttt
    strategy: git
    on:
      repo: solana-labs/example-tictactoe
      branch: custom-testnet
